name: proteus_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - metis=5.1.1
  - ptscotch=6.0.9
  - mumps-mpi=5.2.1
  - superlu_dist=7.2.0
  - pychrono=7.0.0
  - cffi=1.15.1
  - python=3.10.12
  - eigen
  - hypre=2.28.0
  - pytest=7.4.0
  - parmetis=4.0.3
  - cython=3.0.0
  - parso=0.8.3
  - pip=23.2.1
  - numpy=1.25.1
  - compilers=1.5.2
  - gmsh=4.11.1
  - tbb=2021.5.0
  - tetgen=1.6.0
  - h5py==3.9.0[build=*mpich*]
  - petsc=3.19.3
  - daetk=1.0.1
  - pycparser=2.21
  - setuptools=68.0.0
  - triangle=1.6
  - zoltan=3.901
  - numexpr=2.8.4
  - pytables=3.8.0
  - scorec=2.2.7
  - decorator=5.1.1
  - make=4.3
  - hdf5==1.14.1[build=*mpich*]
  - openblas=0.3.23
  - ncurses=6.4
  - pytest-xdist=3.3.1
  - future=0.18.3
  - mpich-mpicxx=4.1.1
  - pytest-cov=4.1.0
  - matplotlib=3.7.2
  - ipyparallel=8.6.1
  - mpich=4.1.1
  - zipp=3.8.0
  - petsc4py=3.19.2
  - superlu=5.2.2
  - xtensor-python=0.26.1
  - ipython=8.14.0
  - mpi4py=3.1.4
  - pillow=9.4.0
  - scipy=1.11.1
  - mpich-mpicc=4.1.1
  - git-lfs=3.3.0
  - scalapack=2.2.0
  - sympy
  - jupyterlab
  - ipywidgets
  - ipygany
  - ipympl
  - ipydatawidgets
  - proteus